name: Android CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
      - uses: actions/checkout@v3
      
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle
          
      - name: Access OPEN WEATHER MAP key
        env:
          OPEN_WEATHER_MAP_KEY: ${{ secrets.OPEN_WEATHER_MAP_KEY }}
        run: echo OPEN_WEATHER_MAP_KEY=\"$OPEN_WEATHER_MAP_KEY"\ > ./local.properties
        
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        
      - name: Clean
        run: ./gradlew clean
        
      - name: Build with Gradle
        run: ./gradlew build
      
  apk:
    name: Generate APK
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
      - name: Build debug APK
        run: bash ./gradle assembleDebug --stacktrace
